services:
  minio:
    container_name: minio
    image: minio/minio:latest
    env_file:
      - .env.minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    # volumes:
    #   - blob-storage:/etc/data
    # healthcheck:
    #   test: ["CMD", "wget", "--output-document", "-", "http://127.0.0.1:8081/health"]
    #   interval: 5s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s
volumes:
  minio_data:
    driver: local